### ISSUE TITLE
Allow Emerald With Different Names

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [MinecraftWars/Gringotts#147]
Hi.
I want that gringotts actually count the emerald item with the name "&a&l$ Emerald" and with the lore "&ewww.guardianmc.net", only normal emeralds are counted.

**Comment by jastice** [comment]
Have you configured it as described in the config instructions? Please check if your config is correct, and paste it verbatim if you can't figure it out.

**Comment by QUIQUELHAPPY** [comment]
```
# for details on configuration, see https://github.com/MinecraftWars/Gringotts/blob/master/doc/configuration.md

# supported languages: "custom" (default, english) and "de" (german)
language: custom

# currency name and value config
currency:
  # currency name to use in messages
  name:
    singular: Emerald
    plural: Emeralds

  # number of decimal digits supported by currency value (0 for whole numbers only)
  digits: 2

  # Display account balances with individual denomination names
  named-denominations: false

  # value of individual denominations. default: emerald: 1, emerald block: 9
  denominations:
    - material: emerald
      value: 1
      displayname: '&a&l1$ Emerald'
      lore: '&6www.guardianmc.net'
    - material: emerald_block
      displayname: '&a&l9$ Emerald'
      lore: '&6www.guardianmc.net'
      value: 9

# tax on /money pay transactions
transactiontax:
  flat: 0.0
  rate: 0.0

# balance to start an account with (purely virtual)
startingbalance:
  player: 0
  faction: 0
  town: 0
  nation: 0

# globally (dis)allow use of vault types
usevault:
  container: true
  enderchest: true

# whether money/balance commands show vault and inventory balance separately
balance:
  show-vault: true
  show-inventory: true

```
