### ISSUE TITLE
Optional cost for creating vaults

### ISSUE THREAD

**Issue by jastice** [MinecraftWars/Gringotts#33]
Implement an optional, configurable price for creating Gringotts vaults.
There should be separate prices for player vaults and faction/town vaults.

A configuration could look something like this:

```
vaultprice:
  player: 0
  faction: 10
  towny:
    town: 5
    nation: 100
```
